spring:
  datasource:
    url: $[db_url]
    username: $[db_username]
    password: $[db_password]
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: $[db_schema]

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: $[client_id]
            client-secret: $[client_secret]
            scope:
              - openid
              - profile
              - email
  mail:
    host: smtp.gmail.com
    port: 587
    username: $[gmail_address]
    password: $[gmail_APP_password]


    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true


logging:
  level:
    org.springframework.web: info
    org.springframework.security: debug
